config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tweets#index'
  namespace :tweets do
    resources :searches, only: :index
  end
  resources :tweets do
    resources :comments, only: :create
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet  
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :text, presence: true
  belongs_to :user
  has_many :comments
  def self.search(search)
    if search
      Tweet.where('text LIKE(?)', "%#{search}%")
    else
      Tweet.all
    end
  end
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/tweets/#{comment.tweet.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, tweet_id: params[:tweet_id])
  end
end

app/controllers/tweets/searches_controller.rb
class Tweets::SearchesController < ApplicationController
  def index
    @tweets = Tweet.search(params[:keyword])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :move_to_index, except: [:index, :show]
  def index
    @tweets = Tweet.all.order("created_at DESC").page(params[:page]).per(5)
  end

  def new
    @tweet = Tweet.new
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)
  end

  def create
    Tweet.create(tweet_params)
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    tweet.update(tweet_params)
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
  end

  private
  def tweet_params
       params.require(:tweet).permit(:image, :text).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @nickname = current_user.nickname
    @tweets = current_user.tweets
    @tweets = user.tweets.page(params[:page]).per(5).order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets/searches_helper.rb
module Tweets::SearchesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Momsive</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/livestamp/1.1.0/livestamp.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Baloo+2:wght@700&display=swap" rel="stylesheet">
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>

  <body>
    <div class = "header">
      <div class = "header-upper">
        <div class = "header-upper-title">
        <% if user_signed_in? %>
        <%= link_to current_user.nickname, root_path %>
        <% else %>
          <%= link_to "Momsive", root_path%>
           <% end %>
        </div>
        <% if user_signed_in? %>
          <div class="user">
            <%= link_to "マイページ", "/users/#{current_user.id}", class: "my" %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'out' %>
            <%= link_to  "投稿する", "/tweets/new", class: "post" %>
          </div>
        <% else %>
          <div class="user">
            <%= link_to "ログイン", new_user_session_path, class: 'rog' %>
            <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
          </div>
        <% end %>
        <div class = "header-upper-post">
          <%= link_to "tweet", new_tweet_path %>
        </div>
      </div>
    </div>
    <div class = "contents">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tweets/_form.html.erb
        <%= form.file_field :image %>
        <i class="far fa-image"></i>
        <br>
        <%= form.text_area :text, placeholder: "text" , rows: "10" %>
        <br>
    <%= form.submit "SEND", id: "submit" %>

app/views/tweets/create.html.erb
<div class = "contents-center">
 <div class="success">
    <h2>
      Post has been completed
    </h2>
    <a class="btn" href="/tweets">Return to list of posts</a>
  </div>
  <div class = "contents-side">
      <div class = "contents-side-left">
      </div>
      <div class = "contents-side-right">
      </div>
    </div>
</div>

app/views/tweets/destroy.html.erb
<div class = "contents-center">
  <div class="success">
    <h4>
      Post has been deleted
    </h4>
    <a class="btn" href="/">Return to list of posts</a>
  </div>
</div>
</div>
<div class = "contents-side">
      <div class = "contents-side-left">
      </div>
      <div class = "contents-side-right">
      </div>
    </div>

app/views/tweets/edit.html.erb
 <div class = "contents-new">
      <%= form_with(model: @tweet, local: true, class: "form") do |form| %>
        <h3>
          Tweet-Edit
        </h3>
      <%= render partial: "form", locals: { form: form } %>
      <% end %>
   </div>
    <div class = "contents-side">
      <div class = "contents-side-left">
      </div>
      <div class = "contents-side-right">
      </div>
    </div>
</div>

app/views/tweets/index.html.erb
<% @tweets.each do |tweet| %>
  <div class = "contents-oya">
    <div class = "contents-center">
    <div class = "contents-name-date">
      <div class = "contents-name">
       <%= tweet.user.nickname %>   
      </div>
      <div class = "contents-date">
    <span data-livestamp="<%=tweet.updated_at.strftime("%Y/%m/%d %H:%M %Z")%>"></span>
      </div>
    </div>
      <div class = "contents-post">
        <%= link_to tweet.text, tweet_path(tweet.id), class: "content__right__top--title" %>
        <br>
        <% if tweet.image? %>
        <%= image_tag tweet.image.url %>
        <% end %>
      </div>
    <div class = "contents-side">
      <div class = "contents-side-left">
      </div>
      <div class = "contents-side-right">
      </div>
    </div>
</div>
<% end %>
<div class = "paginate">
  <%= paginate(@tweets) %>
</div>

app/views/tweets/new.html.erb
 <div class = "contents-center">
   <div class = "contents-new">
      <%= form_with(model: @tweet, local: true, class: "form") do |form| %>
        <h3>
          Tweet
        </h3>
     <%= render partial: "form", locals: { form: form } %>
      <% end %>
   </div>
    <div class = "contents-side">
      <div class = "contents-side-left">
      </div>
      <div class = "contents-side-right">
      </div>
    </div>
</div>

app/views/tweets/searches/index.html.erb
<%= form_with(url: tweets_searches_path, local: true, method: :get, class: "search-form") do |form| %>
  <div class = "search">
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
  </div>
<% end %>
<% @tweets.each do |tweet| %>
  <div class = "contents-oya">
    <div class = "contents-center">
    <div class = "contents-name-date">
      <div class = "contents-name">
       <%= tweet.user.nickname %>   
      </div>
      <div class = "contents-date">
    <span data-livestamp="<%=tweet.updated_at.strftime("%Y/%m/%d %H:%M %Z")%>"></span>
      </div>
    </div>
      <div class = "contents-post">
        <%= link_to tweet.text, tweet_path(tweet.id), class: "content__right__top--title" %>
        <br>
        <% if tweet.image? %>
        <%= image_tag tweet.image.url %>
        <% end %>
      </div>
    <div class = "contents-side">
      <div class = "contents-side-left">
      </div>
      <div class = "contents-side-right">
      </div>
    </div>
</div>
<% end %>

app/views/tweets/show.html.erb
<div class = "contents-oya">
    <div class = "contents-center">
    <div class = "contents-name-date">
      <div class = "contents-name-show">
        <%= @tweet.user.nickname %>    
      </div>
      <div class = "contents-date-show">
    <span data-livestamp="<%=@tweet.updated_at.strftime("%Y/%m/%d %H:%M %Z")%>"></span>
      </div>
    </div>
    <% if user_signed_in? && current_user.id == @tweet.user_id %>
    <div class = "edit">
      <%= link_to '編集', "/tweets/#{@tweet.id}/edit", method: :get %>
    </div>
    <div class = "delete">
     <%= link_to '削除', "/tweets/#{@tweet.id}", method: :delete %>
     </div>
     <% end %>
      <div class = "contents-post-show">
        <%= @tweet.text%>
        <br>
        <% if @tweet.image? %>
        <%= image_tag @tweet.image.url, class: "show" %>
        <% end %>
      </div>
        <div class="container">
    <% if current_user %>
      <%= form_with(model: [@tweet, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
        <br>
        <%= form.submit "SEND", class: "comment_btn" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
  </div>
      <div class="comments">
      <h6>＜コメント一覧＞</h6>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
            <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
            <%= comment.text %>
          </p>
        <% end %>
      <% end %>
    </div>
    <div class = "contents-side">
      <div class = "contents-side-left">
      </div>
      <div class = "contents-side-right">
      </div>
    </div>
</div>

app/views/tweets/update.html.erb
<div class = "contents-new">
<div class="success">
    <h5>
      completed edit
    </h5>
    <a class="btn" href="/">Return to list of posts</a>
  </div>
</div>
<div class = "contents-side">
      <div class = "contents-side-left">
      </div>
      <div class = "contents-side-right">
      </div>
    </div>

app/views/users/show.html.erb
<h5><%= @nickname%>さんの投稿</h1>
<% @tweets.each do |tweet| %>

<div class = "contents-oya">
    <div class = "contents-center2">
    <div class = "contents-name-date">
      <div class = "contents-date2">
    <span data-livestamp="<%=tweet.updated_at.strftime("%Y/%m/%d %H:%M %Z")%>"></span>
      </div>
    </div>
      <div class = "contents-post2">
        <%= link_to tweet.text, tweet_path(tweet.id), class: "content__right__top--title" %>
        <br>
        <% if tweet.image? %>
        <%= image_tag tweet.image.url %>
        <% end %>
      </div>
    <div class = "contents-side">
      <div class = "contents-side-left">
      </div>
      <div class = "contents-side-right">
      </div>
    </div>
</div>
<% end %>
<div class = "paginate">
  <%= paginate(@tweets) %>
</div>